<?php

namespace Popolitinero\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BusTourExceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusTourExceptionRepository extends EntityRepository
{
}