<?php

namespace Popolitinero\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BusTourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusTourRepository extends EntityRepository
{
}