<?php

namespace Popolitinero\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HubRepository extends EntityRepository
{
    public function getBarycenter($hubslug = null)
    {
      if($hubslug):
        return $this->getEntityManager()->createQuery('
          SELECT (MIN(b.latitude)+MAX(b.latitude))/2 AS latitude, (MIN(b.longitude)+MAX(b.longitude))/2 AS longitude
          FROM PopolitineroDefaultBundle:Hub h
          LEFT JOIN h.cities c
          LEFT JOIN c.nevralg
          WHERE h.slug = ?1')
          ->setParameter(1, $hubslug)
          ->getSingleResult();
      else:
        return $this->getEntityManager()->createQuery('
          SELECT (MIN(b.latitude)+MAX(b.latitude))/2 AS latitude, (MIN(b.longitude)+MAX(b.longitude))/2 AS longitude
          FROM PopolitineroDefaultBundle:Hub h
          LEFT JOIN h.cities c          
          LEFT JOIN c.nevralgic_point b')
          ->getSingleResult();
      endif;
    }
}
