<?php

namespace Popolitinero\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HubRepository extends EntityRepository
{
    public function getBarycenter($hubslug = null)
    {
      if($hubslug):
        return $this->getEntityManager()->createQuery('
          SELECT (MIN(c.latitude)+MAX(c.latitude))/2 AS latitude, (MIN(c.longitude)+MAX(c.longitude))/2 AS longitude
          FROM PopolitineroDefaultBundle:Hub h
          LEFT JOIN h.cities c
          WHERE h.slug = ?1')
          ->setParameter(1, $hubslug)
          ->getSingleResult();
      else:
        return $this->getEntityManager()->createQuery('
          SELECT (MIN(c.latitude)+MAX(c.latitude))/2 AS latitude, (MIN(c.longitude)+MAX(c.longitude))/2 AS longitude
          FROM PopolitineroDefaultBundle:Hub h
          LEFT JOIN h.cities c')
          ->getSingleResult();
      endif;
    }
}
